// Copyright 2026 the Parley Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Native build-time tool: reads `NotoColorEmoji-Regular.ttf`'s cmap + hmtx and emits a
//! generated Rust source file `NOTO_UPEM` + `NOTO_ADVANCES: &[(u32, u16)]`, sorted by
//! codepoint. Not committed; run manually:
//!
//! ```sh
//! cargo run -p noto_advance_gen -- <out.rs>
//! ```

use std::fmt::Write as _;
use std::path::PathBuf;

use skrifa::raw::TableProvider;
use skrifa::{FontRef, MetadataProvider};

const NOTO_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../../../parley_dev/assets/fonts/noto_color_emoji/NotoColorEmoji-Regular.ttf"
);

fn main() {
    let mut args = std::env::args_os().skip(1);
    let out_path: PathBuf = args
        .next()
        .expect("usage: noto_advance_gen <out.rs>")
        .into();

    let bytes = std::fs::read(NOTO_PATH).unwrap_or_else(|e| panic!("failed to read {NOTO_PATH}: {e}"));
    let font = FontRef::new(&bytes).expect("failed to parse font");
    let upem = font.head().expect("no head table").units_per_em();
    let charmap = font.charmap();
    let hmtx = font.hmtx().expect("no hmtx table");

    let mut rows: Vec<(u32, u16)> = Vec::new();
    for (cp, gid) in charmap.mappings() {
        let advance = hmtx
            .advance(gid)
            .unwrap_or(0);
        rows.push((cp, advance));
    }
    rows.sort_by_key(|&(cp, _)| cp);
    rows.dedup_by_key(|&mut (cp, _)| cp);

    let mut out = String::new();
    out.push_str("// GENERATED by noto_advance_gen — do not edit. (uncommitted)\n");
    let _ = writeln!(out, "pub(crate) const NOTO_UPEM: u16 = {upem};");
    let _ = writeln!(
        out,
        "/// (codepoint, `advance_in_font_units`), sorted ascending by codepoint."
    );
    let _ = writeln!(out, "pub(crate) const NOTO_ADVANCES: &[(u32, u16)] = &[");
    for (cp, adv) in &rows {
        let _ = writeln!(out, "    (0x{cp:X}, {adv}),");
    }
    out.push_str("];\n");

    std::fs::write(&out_path, out).unwrap_or_else(|e| panic!("failed to write {out_path:?}: {e}"));

    eprintln!(
        "wrote {} entries (upem={upem}) to {out_path:?}",
        rows.len()
    );
}
